// <auto-generated />
namespace Axure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:back_end/Axure/Migrations/202005031809478_initial.Designer.cs
            get { return "202005031809478_initial"; }
=======
            get { return "202005050009307_Initial"; }
>>>>>>> master:back_end/Axure/Migrations/202005050009307_Initial.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
